export { default as Home } from '../pages/home/Home';
export { default as About } from '../pages/about/About';
export { default as Posts } from '../pages/post/Posts';
export { default as Post } from '../pages/post/Post';
export { default as Interview } from '../pages/interview/Interview';
export { default as Conference } from '../pages/conference/Conference';;
export { default as Stores } from '../pages/store/Stores';
export { default as Store } from '../pages/store/Store';
export { default as Contactus } from '../pages/contactus/Contactus';