export { default as Home } from './Home';
export { default as About } from './About';
export { default as Posts } from './Posts';
export { default as Post } from './Post';
export { default as Interview } from './Interview';
export { default as Conference } from './Conference';;
export { default as Stores } from './Stores';
export { default as Store } from './Store';
export { default as Contactus } from './Contactus';